version: '2.1'
services:
  taurus-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTH_URL:  ${AUTH_URL}
      DATA_URL:  ${DATA_URL}
      MATCH_URL: ${MATCH_URL}
      GRID_URL:  ${GRID_URL}
      GAME_URL:  ${GAME_URL}
    ports:
      - '5000:5000'
    networks:
      - taurus-network

networks:
  taurus-network:
    name: taurus-network
    driver: bridge
