version: '2.1'
services:
  taurus-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTH_URL:  taurus-auth-ms
      DATA_URL:  taurus-data-store-ms
      MATCH_URL: taurus-matchmaking-ms
      GRID_URL:  taurus-grid-gen-ms
      GAME_URL:  ec2-3-231-146-168.compute-1.amazonaws.com/gs
      AUTH_USERS_ENTRY: 'taurus-auth-ms/resources/users'
    ports:
      - '5000:5000'
    networks:
      - taurus-network

networks:
  taurus-network:
    name: taurus-network
    driver: bridge
